services:
  cach:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    ports :
      - '6379:6379'
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
